name: Setup Swift
description: Set up Swift environment and cache Swift packages

runs:
  using: composite
  steps:
    - name: Read Swift Version
      id: swift-version
      run: echo "version=$(cat .swift-version)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup Swift
      uses: swift-actions/setup-swift@v3
      with:
        swift-version: ${{ steps.swift-version.outputs.version }}

    - name: Cache Swift Packages
      uses: actions/cache@v5
      with:
        path: |
          .build
          ~/Library/Caches/org.swift.swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-