// This file is automatically generated by scripts/generate-version.sh
// Do not edit manually - changes will be overwritten

extension Constants {
    /// Version extracted from git tags
    public static let version = "0.0.0-dev"
}
