#!/bin/bash
set -e

# Script to generate version from git tags
# This ensures the version is always in sync with git tags

OUTPUT_FILE="Sources/Constants/Version.generated.swift"

# Get the latest git tag, or fallback to "0.0.0-dev" if no tags are found
VERSION=$(git describe --tags --dirty --always 2>/dev/null || echo "0.0.0-dev")

# Generate Swift file
cat > "$OUTPUT_FILE" << EOF
// This file is automatically generated by scripts/generate-version.sh
// Do not edit manually - changes will be overwritten

public extension Constants {
    /// Version extracted from git tags
    static let version = "$VERSION"
}
EOF

echo "✅ Generated version: $VERSION"
