#!/bin/bash
set -e


OUTPUT_FILE="Sources/Constants/Version.generated.swift"

# Version precedence:
# 1. First CLI argument
# 2. VERSION env var
# 3. Fallback
VERSION="${1:-${VERSION:-0.0.0-dev}}"

# Generate Swift file
cat > "$OUTPUT_FILE" << EOF
// This file is automatically generated by scripts/generate-version.sh
// Do not edit manually - changes will be overwritten

public extension Constants {
    /// Version extracted from git tags
    static let version = "$VERSION"
}
EOF

echo "✅ Generated version: $VERSION"
